name: docker build for LUKSO faucet

on:
  push:
    tags:
      - '*'
jobs:
  geth-client-go:
    runs-on: ubuntu-latest

    # id token
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - # check out the repository
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: "Set up Cloud SDK"
        uses: "google-.github-actions/setup-gcloud@v0"

      - # https://github.com/google-github-actions/auth#setup
        id: gcpauth
        name: Authenticate to Google Cloud
        uses: google-.github-actions/auth@v0
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/311968610280/locations/global/workloadIdentityPools/.github/providers/.github"
          service_account: "artifact-deployer@lks-lz-management.iam.gserviceaccount.com"

      - # login to gcp
        name: login
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.gcpauth.outputs.credentials_file_path }}"
          gcloud auth configure-docker europe-docker.pkg.dev
      - # extract tag name
        name: Extract tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Geth Client GO
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            europe-docker.pkg.dev/lks-lz-artifacts/docker-faucet/faucet:${{env.TAG}}